// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: email.sql

package query

import (
	"context"
	"database/sql"
)

const countEmails = `-- name: CountEmails :one
SELECT COUNT(*) FROM emails WHERE uid = ?
`

func (q *Queries) CountEmails(ctx context.Context, uid int64) (int64, error) {
	row := q.queryRow(ctx, q.countEmailsStmt, countEmails, uid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmail = `-- name: CreateEmail :execresult
INSERT INTO emails (address, uid, verified) VALUES (?, ?, false)
`

type CreateEmailParams struct {
	Address string
	UID     int64
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (sql.Result, error) {
	return q.exec(ctx, q.createEmailStmt, createEmail, arg.Address, arg.UID)
}

const deleteEmail = `-- name: DeleteEmail :exec
DELETE FROM emails WHERE id = ?
`

func (q *Queries) DeleteEmail(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteEmailStmt, deleteEmail, id)
	return err
}

const getEmail = `-- name: GetEmail :one
SELECT address, verified, uid, id, created_at, updated_at FROM emails WHERE id = ?
`

func (q *Queries) GetEmail(ctx context.Context, id int64) (Email, error) {
	row := q.queryRow(ctx, q.getEmailStmt, getEmail, id)
	var i Email
	err := row.Scan(
		&i.Address,
		&i.Verified,
		&i.UID,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailByAddressForUser = `-- name: GetEmailByAddressForUser :one
SELECT address, verified, uid, id, created_at, updated_at FROM emails WHERE address = ? AND uid = ?
`

type GetEmailByAddressForUserParams struct {
	Address string
	UID     int64
}

func (q *Queries) GetEmailByAddressForUser(ctx context.Context, arg GetEmailByAddressForUserParams) (Email, error) {
	row := q.queryRow(ctx, q.getEmailByAddressForUserStmt, getEmailByAddressForUser, arg.Address, arg.UID)
	var i Email
	err := row.Scan(
		&i.Address,
		&i.Verified,
		&i.UID,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerifiedEmailByAddress = `-- name: GetVerifiedEmailByAddress :one
SELECT address, verified, uid, id, created_at, updated_at FROM emails WHERE address = ? AND verified = true
`

func (q *Queries) GetVerifiedEmailByAddress(ctx context.Context, address string) (Email, error) {
	row := q.queryRow(ctx, q.getVerifiedEmailByAddressStmt, getVerifiedEmailByAddress, address)
	var i Email
	err := row.Scan(
		&i.Address,
		&i.Verified,
		&i.UID,
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmails = `-- name: ListEmails :many
SELECT address, verified, uid, id, created_at, updated_at FROM emails WHERE uid = ?
`

func (q *Queries) ListEmails(ctx context.Context, uid int64) ([]Email, error) {
	rows, err := q.query(ctx, q.listEmailsStmt, listEmails, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.Address,
			&i.Verified,
			&i.UID,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedEmails = `-- name: ListVerifiedEmails :many
SELECT address, verified, uid, id, created_at, updated_at FROM emails WHERE uid = ? AND verified = true
`

func (q *Queries) ListVerifiedEmails(ctx context.Context, uid int64) ([]Email, error) {
	rows, err := q.query(ctx, q.listVerifiedEmailsStmt, listVerifiedEmails, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.Address,
			&i.Verified,
			&i.UID,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE emails SET verified = true WHERE id = ?
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.markEmailVerifiedStmt, markEmailVerified, id)
	return err
}
