// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package query

import (
	"database/sql"
)

type Email struct {
	Address   string
	Verified  int64
	UID       int64
	ID        int64
	CreatedAt sql.NullInt64
	UpdatedAt sql.NullInt64
}

type User struct {
	PwHash    string
	Username  string
	ID        int64
	CreatedAt sql.NullInt64
	UpdatedAt sql.NullInt64
}

type UserPermission struct {
	Name      string
	IUID      int64
	UID       int64
	ID        int64
	CreatedAt sql.NullInt64
}

type UserPermissionGrant struct {
	Name      string
	IUID      int64
	UID       int64
	ID        int64
	CreatedAt sql.NullInt64
}

type UserPermissionRevocation struct {
	Name      string
	IUID      int64
	UID       int64
	ID        int64
	CreatedAt sql.NullInt64
}

type UserSetting struct {
	Theme     string
	UID       int64
	ID        int64
	CreatedAt sql.NullInt64
	UpdatedAt sql.NullInt64
}
